"""
SIC (Standard Industrial Classification) code mappings.

Major Group (2-digit) and Industry (4-digit) descriptions from the SEC.
"""

# 2-digit Major Group descriptions
SIC_MAJOR_GROUPS = {
    "01": "Crops",
    "02": "Livestock",
    "07": "Agricultural Services",
    "08": "Forestry",
    "09": "Fishing, Hunting & Trapping",
    "10": "Metal Mining",
    "12": "Coal Mining",
    "13": "Oil & Gas Extraction",
    "14": "Nonmetallic Minerals Mining",
    "15": "General Building Contractors",
    "16": "Heavy Construction",
    "17": "Special Trade Contractors",
    "20": "Food & Kindred Products",
    "21": "Tobacco Products",
    "22": "Textile Mill Products",
    "23": "Apparel & Other Textile Products",
    "24": "Lumber & Wood Products",
    "25": "Furniture & Fixtures",
    "26": "Paper & Allied Products",
    "27": "Printing & Publishing",
    "28": "Chemicals & Allied Products",
    "29": "Petroleum Refining",
    "30": "Rubber & Plastics Products",
    "31": "Leather & Leather Products",
    "32": "Stone, Clay, Glass & Concrete",
    "33": "Primary Metal Industries",
    "34": "Fabricated Metal Products",
    "35": "Industrial & Commercial Machinery",
    "36": "Electronic & Electrical Equipment",
    "37": "Transportation Equipment",
    "38": "Measuring & Analyzing Instruments",
    "39": "Miscellaneous Manufacturing",
    "40": "Railroad Transportation",
    "41": "Local & Suburban Transit",
    "42": "Motor Freight & Warehousing",
    "43": "U.S. Postal Service",
    "44": "Water Transportation",
    "45": "Air Transportation",
    "46": "Pipelines, Except Natural Gas",
    "47": "Transportation Services",
    "48": "Communications",
    "49": "Electric, Gas & Sanitary Services",
    "50": "Durable Goods Wholesale",
    "51": "Nondurable Goods Wholesale",
    "52": "Building Materials & Garden Supplies",
    "53": "General Merchandise Stores",
    "54": "Food Stores",
    "55": "Auto Dealers & Gas Stations",
    "56": "Apparel & Accessory Stores",
    "57": "Furniture & Home Furnishings Stores",
    "58": "Eating & Drinking Places",
    "59": "Miscellaneous Retail",
    "60": "Depository Institutions",
    "61": "Nondepository Credit Institutions",
    "62": "Security & Commodity Brokers",
    "63": "Insurance Carriers",
    "64": "Insurance Agents & Brokers",
    "65": "Real Estate",
    "67": "Holding & Other Investment Offices",
    "70": "Hotels & Lodging",
    "72": "Personal Services",
    "73": "Business Services",
    "75": "Auto Repair & Services",
    "76": "Miscellaneous Repair Services",
    "78": "Motion Pictures",
    "79": "Amusement & Recreation Services",
    "80": "Health Services",
    "81": "Legal Services",
    "82": "Educational Services",
    "83": "Social Services",
    "84": "Museums & Galleries",
    "86": "Membership Organizations",
    "87": "Engineering & Management Services",
    "89": "Miscellaneous Services",
    "91": "Executive & Legislative",
    "92": "Justice, Public Order & Safety",
    "93": "Public Finance",
    "94": "Administration of Human Resources",
    "95": "Environmental Quality Administration",
    "96": "Administration of Economic Programs",
    "97": "National Security & International Affairs",
}

# Common 4-digit SIC codes with specific descriptions (SEC filer universe)
SIC_INDUSTRIES = {
    "0100": "Crops",
    "0200": "Livestock & Animal Specialties",
    "0700": "Agricultural Services",
    "0900": "Fishing, Hunting & Trapping",
    "1000": "Metal Mining",
    "1040": "Gold & Silver Ores Mining",
    "1090": "Metal Mining Services",
    "1220": "Bituminous Coal Mining",
    "1221": "Bituminous Coal & Lignite Surface Mining",
    "1311": "Crude Petroleum & Natural Gas",
    "1381": "Drilling Oil & Gas Wells",
    "1382": "Oil & Gas Field Services",
    "1389": "Services Allied to Oil & Gas Extraction",
    "1400": "Nonmetallic Minerals, Except Fuels",
    "1520": "General Building Contractors -Residential",
    "1531": "Operative Builders",
    "1540": "General Building Contractors -Nonresidential",
    "1600": "Heavy Construction, Except Building",
    "1623": "Water, Sewer, Pipeline Construction",
    "1700": "Construction -Special Trade",
    "1731": "Electrical Work",
    "2000": "Food & Kindred Products",
    "2011": "Meat Packing Plants",
    "2013": "Sausages & Other Prepared Meats",
    "2015": "Poultry Slaughtering & Processing",
    "2020": "Dairy Products",
    "2024": "Ice Cream & Frozen Desserts",
    "2030": "Canned, Frozen & Preserved Fruits & Vegetables",
    "2033": "Canned Fruits, Vegetables & Preserves",
    "2040": "Grain Mill Products",
    "2050": "Bakery Products",
    "2060": "Sugar & Confectionery Products",
    "2070": "Fats & Oils",
    "2080": "Beverages",
    "2086": "Bottled & Canned Soft Drinks",
    "2090": "Misc Food Products & Kindred Products",
    "2100": "Tobacco Products",
    "2111": "Cigarettes",
    "2200": "Textile Mill Products",
    "2211": "Broadwoven Fabric Mills, Cotton",
    "2221": "Broadwoven Fabric Mills, Manmade Fiber",
    "2250": "Knitting Mills",
    "2253": "Knit Outerwear Mills",
    "2273": "Carpets & Rugs",
    "2300": "Apparel & Other Finished Products",
    "2320": "Men's & Boys' Furnishings",
    "2330": "Women's, Misses' & Juniors' Outerwear",
    "2340": "Children's Outerwear",
    "2390": "Fabricated Textile Products",
    "2400": "Lumber & Wood Products",
    "2421": "Sawmills & Planing Mills",
    "2430": "Millwork, Veneer, Plywood & Structural Members",
    "2451": "Mobile Homes",
    "2510": "Household Furniture",
    "2511": "Wood Household Furniture",
    "2520": "Office Furniture",
    "2531": "Public Building & Related Furniture",
    "2590": "Misc Furniture & Fixtures",
    "2600": "Paper & Allied Products",
    "2611": "Pulp Mills",
    "2621": "Paper Mills",
    "2631": "Paperboard Mills",
    "2650": "Paperboard Containers & Boxes",
    "2670": "Converted Paper & Paperboard Products",
    "2710": "Newspapers: Publishing & Printing",
    "2711": "Newspapers: Publishing & Printing",
    "2720": "Periodicals: Publishing & Printing",
    "2731": "Books: Publishing & Printing",
    "2732": "Book Printing",
    "2740": "Miscellaneous Publishing",
    "2750": "Commercial Printing",
    "2761": "Manifold Business Forms",
    "2780": "Blankbooks, Looseleaf Binders & Devices",
    "2790": "Services Allied to Printing",
    "2800": "Chemicals & Allied Products",
    "2810": "Industrial Chemicals & Synthetics",
    "2820": "Plastics & Synthetic Resins",
    "2821": "Plastics Materials & Resins",
    "2833": "Pharmaceutical Preparations",
    "2834": "Pharmaceutical Preparations",
    "2835": "In Vitro & In Vivo Diagnostics",
    "2836": "Biological Products, Except Diagnostics",
    "2840": "Soap, Detergent & Cleaning Preparations",
    "2842": "Specialty Cleaning & Polishing Preparations",
    "2844": "Perfumes, Cosmetics & Toilet Preparations",
    "2851": "Paints, Varnishes & Lacquers",
    "2860": "Industrial Chemicals & Synthetics",
    "2870": "Agricultural Chemicals",
    "2890": "Misc Chemical Products",
    "2891": "Adhesives & Sealants",
    "2911": "Petroleum Refining",
    "2950": "Asphalt Paving & Roofing Materials",
    "2990": "Misc Petroleum & Coal Products",
    "3011": "Tires & Inner Tubes",
    "3021": "Rubber & Plastics Footwear",
    "3050": "Gaskets, Hoses & Belts",
    "3060": "Fabricated Rubber Products",
    "3080": "Plastics Products Manufacturing",
    "3086": "Plastics Foam Products",
    "3089": "Plastics Products, NEC",
    "3100": "Leather & Leather Products",
    "3140": "Footwear, Except Rubber",
    "3211": "Flat Glass",
    "3220": "Glass & Glassware",
    "3221": "Glass Containers",
    "3231": "Glass Products from Purchased Glass",
    "3241": "Cement, Hydraulic",
    "3250": "Structural Clay Products",
    "3270": "Concrete, Gypsum & Plaster Products",
    "3290": "Nonmetallic Mineral Products",
    "3310": "Steel Works & Blast Furnaces",
    "3312": "Steel Works, Blast Furnaces & Rolling Mills",
    "3317": "Steel Pipe & Tubes",
    "3330": "Primary Smelting of Nonferrous Metals",
    "3334": "Primary Aluminum Production",
    "3341": "Secondary Smelting of Nonferrous Metals",
    "3350": "Rolling & Drawing of Nonferrous Metals",
    "3357": "Drawing & Insulating of Nonferrous Metals",
    "3360": "Nonferrous Foundries",
    "3390": "Misc Primary Metal Products",
    "3411": "Metal Cans",
    "3412": "Metal Shipping Barrels & Drums",
    "3420": "Cutlery, Hand Tools & General Hardware",
    "3430": "Heating Equipment & Plumbing Fixtures",
    "3440": "Fabricated Structural Metal Manufacturing",
    "3442": "Fabricated Plate Work",
    "3443": "Fabricated Plate Work (Boiler Shops)",
    "3444": "Sheet Metal Work",
    "3448": "Prefabricated Metal Buildings & Components",
    "3451": "Screw Machine Products",
    "3460": "Metal Forgings & Stampings",
    "3470": "Services to Metal Finishing",
    "3480": "Ordnance & Accessories",
    "3490": "Misc Fabricated Metal Products",
    "3510": "Engines & Turbines",
    "3523": "Farm Machinery & Equipment",
    "3524": "Lawn & Garden Tractors & Equipment",
    "3530": "Construction & Related Machinery",
    "3531": "Construction Machinery & Equipment",
    "3532": "Mining Machinery & Equipment",
    "3533": "Oil & Gas Field Machinery & Equipment",
    "3537": "Industrial Trucks, Tractors & Trailers",
    "3540": "Metalworking Machinery & Equipment",
    "3541": "Machine Tools, Metal Cutting Types",
    "3550": "Special Industry Machinery",
    "3555": "Printing Trades Machinery & Equipment",
    "3559": "Special Industry Machinery, NEC",
    "3560": "General Industrial Machinery & Equipment",
    "3561": "Pumps & Pumping Equipment",
    "3562": "Ball & Roller Bearings",
    "3564": "Industrial & Commercial Fans & Blowers",
    "3567": "Industrial Process Furnaces & Ovens",
    "3569": "General Industrial Machinery & Equipment, NEC",
    "3570": "Computer & Office Equipment",
    "3571": "Electronic Computers",
    "3572": "Computer Storage Devices",
    "3575": "Computer Terminals",
    "3576": "Computer Communications Equipment",
    "3577": "Computer Peripheral Equipment, NEC",
    "3578": "Calculating & Accounting Machines",
    "3579": "Office Machines, NEC",
    "3580": "Refrigeration & Service Industry Machinery",
    "3585": "Air-Conditioning & Heating Equipment",
    "3589": "Industrial & Commercial Machinery, NEC",
    "3590": "Misc Industrial & Commercial Machinery",
    "3599": "Industrial & Commercial Machinery, NEC",
    "3612": "Power, Distribution & Specialty Transformers",
    "3613": "Switchgear & Switchboard Apparatus",
    "3620": "Electrical Industrial Apparatus",
    "3621": "Motors & Generators",
    "3630": "Household Appliances",
    "3634": "Housewares & Fans",
    "3640": "Electric Lighting & Wiring Equipment",
    "3651": "Household Audio & Video Equipment",
    "3652": "Prerecorded Records & Tapes",
    "3661": "Telephone & Telegraph Apparatus",
    "3663": "Radio & TV Broadcasting & Communications Equipment",
    "3669": "Communications Equipment, NEC",
    "3670": "Electronic Components & Accessories",
    "3672": "Printed Circuit Boards",
    "3674": "Semiconductors & Related Devices",
    "3677": "Electronic Coils, Transformers & Inductors",
    "3678": "Electronic Connectors",
    "3679": "Electronic Components, NEC",
    "3690": "Misc Electrical Machinery & Equipment",
    "3695": "Magnetic & Optical Recording Media",
    "3699": "Electrical Machinery & Equipment, NEC",
    "3711": "Motor Vehicles & Passenger Car Bodies",
    "3713": "Truck Trailers",
    "3714": "Motor Vehicle Parts & Accessories",
    "3715": "Truck Trailers",
    "3716": "Motor Homes",
    "3720": "Aircraft & Parts",
    "3721": "Aircraft",
    "3724": "Aircraft Engines & Engine Parts",
    "3728": "Aircraft Parts & Auxiliary Equipment, NEC",
    "3730": "Ship & Boat Building & Repairing",
    "3743": "Railroad Equipment",
    "3751": "Motorcycles, Bicycles & Parts",
    "3760": "Guided Missiles & Space Vehicles",
    "3769": "Guided Missiles & Space Vehicles, NEC",
    "3790": "Misc Transportation Equipment",
    "3812": "Defense Electronics & Communications",
    "3821": "Laboratory Apparatus & Furniture",
    "3822": "Automatic Controls for HVAC",
    "3823": "Industrial Instruments for Measurement",
    "3824": "Industrial Instruments for Measurement",
    "3825": "Instruments for Measuring & Testing",
    "3826": "Laboratory Analytical Instruments",
    "3827": "Optical Instruments & Lenses",
    "3829": "Measuring & Controlling Devices, NEC",
    "3841": "Surgical & Medical Instruments & Apparatus",
    "3842": "Orthopedic, Prosthetic & Surgical Supplies",
    "3843": "Dental Equipment & Supplies",
    "3844": "X-Ray Apparatus & Tubes",
    "3845": "Electromedical & Electrotherapeutic Apparatus",
    "3851": "Ophthalmic Goods",
    "3861": "Photographic Equipment & Supplies",
    "3873": "Watches, Clocks & Parts",
    "3911": "Jewelry & Precious Metal",
    "3931": "Musical Instruments",
    "3942": "Dolls & Stuffed Toys",
    "3944": "Games, Toys & Children's Vehicles",
    "3949": "Sporting & Athletic Goods, NEC",
    "3990": "Miscellaneous Manufacturing Industries",
    "3993": "Signs & Advertising Specialties",
    "3999": "Manufacturing Industries, NEC",
    "4011": "Railroads, Line-Haul Operating",
    "4013": "Railroad Switching & Terminal",
    "4100": "Local & Suburban Transit",
    "4210": "Trucking & Courier Services",
    "4213": "Trucking, Except Local",
    "4220": "Public Warehousing & Storage",
    "4231": "Terminal & Joint Terminal Maintenance",
    "4400": "Water Transportation",
    "4412": "Deep Sea Foreign Transportation of Freight",
    "4512": "Air Transportation, Scheduled",
    "4522": "Air Transportation, Nonscheduled",
    "4581": "Airports, Flying Fields & Airport Services",
    "4610": "Pipelines, Except Natural Gas",
    "4700": "Transportation Services",
    "4731": "Freight Transportation Arrangement",
    "4812": "Radiotelephone Communications",
    "4813": "Telephone Communications",
    "4822": "Telegraph & Other Message Communications",
    "4832": "Radio Broadcasting Stations",
    "4833": "Television Broadcasting Stations",
    "4841": "Cable & Other Pay Television Services",
    "4899": "Communications Services, NEC",
    "4900": "Electric, Gas & Sanitary Services",
    "4911": "Electric Services",
    "4922": "Natural Gas Distribution",
    "4923": "Natural Gas Transmission & Distribution",
    "4924": "Natural Gas Distribution",
    "4931": "Electric & Other Services Combined",
    "4932": "Gas & Other Services Combined",
    "4941": "Water Supply",
    "4950": "Sanitary Services",
    "4953": "Refuse Systems",
    "4955": "Hazardous Waste Management",
    "4991": "Cogeneration & Small Power Producers",
    "5000": "Durable Goods -Wholesale",
    "5010": "Motor Vehicles & Motor Vehicle Parts",
    "5013": "Motor Vehicle Supplies & New Parts",
    "5020": "Furniture & Home Furnishings",
    "5030": "Lumber & Other Construction Materials",
    "5040": "Professional & Commercial Equipment",
    "5045": "Computers & Computer Peripherals",
    "5047": "Medical & Hospital Equipment",
    "5050": "Metals & Minerals, Except Petroleum",
    "5051": "Metals Service Centers & Offices",
    "5063": "Electrical Apparatus & Equipment",
    "5064": "Electrical Appliances, TV & Radio Sets",
    "5065": "Electronic Parts & Equipment",
    "5070": "Hardware & Plumbing & Heating Equipment",
    "5080": "Machinery, Equipment & Supplies",
    "5084": "Industrial Machinery & Equipment",
    "5090": "Durable Goods, NEC",
    "5094": "Jewelry, Watches & Precious Stones",
    "5099": "Durable Goods, NEC",
    "5110": "Paper & Paper Products",
    "5122": "Drugs, Drug Proprietaries & Sundries",
    "5130": "Apparel, Piece Goods & Notions",
    "5140": "Groceries & Related Products",
    "5141": "Groceries, General Line",
    "5150": "Farm-Product Raw Materials",
    "5160": "Chemicals & Allied Products",
    "5169": "Chemicals & Allied Products, NEC",
    "5171": "Petroleum & Petroleum Products (Wholesale)",
    "5172": "Petroleum & Petroleum Products, NEC",
    "5180": "Beer, Wine & Distilled Alcoholic Beverages",
    "5190": "Misc Nondurable Goods",
    "5200": "Building Materials & Supplies -Retail",
    "5211": "Lumber & Other Building Materials Dealers",
    "5271": "Mobile Home Dealers",
    "5311": "Department Stores",
    "5331": "Variety Stores",
    "5399": "Misc General Merchandise Stores",
    "5400": "Food Stores",
    "5411": "Grocery Stores",
    "5412": "Convenience Stores",
    "5500": "Auto Dealers & Gas Stations",
    "5531": "Auto & Home Supply Stores",
    "5600": "Apparel & Accessory Stores",
    "5621": "Women's Clothing Stores",
    "5651": "Family Clothing Stores",
    "5661": "Shoe Stores",
    "5700": "Home Furniture & Furnishings Stores",
    "5712": "Furniture Stores",
    "5731": "Radio, Television & Consumer Electronics Stores",
    "5734": "Computer & Computer Software Stores",
    "5735": "Record & Prerecorded Tape Stores",
    "5810": "Eating & Drinking Places",
    "5812": "Eating Places",
    "5900": "Retail Stores, NEC",
    "5912": "Drug Stores & Proprietary Stores",
    "5940": "Sporting Goods & Hobby Stores",
    "5944": "Jewelry Stores",
    "5945": "Hobby, Toy & Game Shops",
    "5947": "Gift, Novelty & Souvenir Shops",
    "5960": "Retail -Nonstore Retailers",
    "5961": "Catalog & Mail-Order Houses",
    "5990": "Retail Stores, NEC",
    "6020": "State Commercial Banks -Federal Reserve Members",
    "6021": "National Commercial Banks",
    "6022": "State Commercial Banks",
    "6029": "Commercial Banks, NEC",
    "6035": "Savings Institution, Federally Chartered",
    "6036": "Savings Institutions, Not Federally Chartered",
    "6099": "Functions Related to Depository Banking",
    "6111": "Federal & Federally-Sponsored Credit Agencies",
    "6120": "Savings Institutions, Federally Chartered",
    "6141": "Personal Credit Institutions",
    "6153": "Short-Term Business Credit Institutions",
    "6159": "Federal-Sponsored Credit Agencies",
    "6162": "Mortgage Bankers & Loan Correspondents",
    "6163": "Loan Brokers",
    "6199": "Finance Services",
    "6200": "Security & Commodity Services",
    "6211": "Security Brokers & Dealers",
    "6221": "Commodity Contracts Dealers & Brokers",
    "6282": "Investment Advice",
    "6311": "Life Insurance",
    "6321": "Accident & Health Insurance",
    "6324": "Hospital & Medical Service Plans",
    "6331": "Fire, Marine & Casualty Insurance",
    "6351": "Surety Insurance",
    "6399": "Insurance Carriers, NEC",
    "6411": "Insurance Agents, Brokers & Service",
    "6500": "Real Estate",
    "6510": "Real Estate Operators & Lessors",
    "6512": "Operators of Apartment Buildings",
    "6519": "Real Property Lessors, NEC",
    "6531": "Real Estate Agents & Managers",
    "6532": "Real Estate Dealers",
    "6552": "Land Subdividers & Developers",
    "6600": "Combined Real Estate, Insurance, etc.",
    "6710": "Holding Offices",
    "6720": "Investment Offices, NEC",
    "6726": "Investment Offices, NEC",
    "6770": "Blank Checks",
    "6792": "Management Investment Companies, Open-End",
    "6794": "Patent Owners & Lessors",
    "6795": "Trusts, NEC",
    "6798": "Real Estate Investment Trusts",
    "6799": "Investors, NEC",
    "7000": "Hotels, Rooming Houses & Camps",
    "7011": "Hotels & Motels",
    "7200": "Personal Services",
    "7310": "Services to Buildings & Dwellings",
    "7311": "Advertising Services",
    "7320": "Services to Buildings & Dwellings",
    "7330": "Mailing, Reproduction & Stenographic Services",
    "7340": "Services to Buildings & Dwellings",
    "7350": "Misc Equipment Rental & Leasing",
    "7359": "Equipment Rental & Leasing, NEC",
    "7361": "Help Supply Services",
    "7363": "Help Supply Services",
    "7370": "Computer Programming & Data Processing",
    "7371": "Computer Programming Services",
    "7372": "Prepackaged Software",
    "7373": "Computer Integrated Systems Design",
    "7374": "Computer Processing & Data Preparation",
    "7377": "Computer Rental & Leasing",
    "7380": "Miscellaneous Business Services",
    "7381": "Investigation & Security Services",
    "7384": "Photofinishing Laboratories",
    "7389": "Misc Business Services, NEC",
    "7500": "Automotive Repair, Services & Parking",
    "7510": "Automotive Rentals",
    "7600": "Miscellaneous Repair Services",
    "7812": "Motion Picture Production & Distribution",
    "7819": "Services Allied to Motion Picture Production",
    "7822": "Motion Picture Distribution & Services",
    "7841": "Video Tape Rental",
    "7900": "Amusement & Recreation Services",
    "7941": "Professional Sports Clubs",
    "7948": "Racing, Including Track Operation",
    "7990": "Misc Amusement & Recreation",
    "7993": "Coin-Operated Amusement Devices",
    "7996": "Amusement Parks",
    "7997": "Membership Sports & Recreation Clubs",
    "8000": "Health Services",
    "8011": "Offices & Clinics of Doctors of Medicine",
    "8020": "Offices & Clinics of Dentists",
    "8040": "Offices of Other Health Practitioners",
    "8042": "Offices & Clinics of Optometrists",
    "8049": "Offices of Other Health Practitioners, NEC",
    "8050": "Nursing & Personal Care Facilities",
    "8051": "Skilled Nursing Care Facilities",
    "8060": "Hospitals",
    "8062": "General Medical & Surgical Hospitals",
    "8071": "Health Services",
    "8082": "Home Health Care Services",
    "8090": "Health Services, NEC",
    "8093": "Specialty Outpatient Facilities, NEC",
    "8099": "Health Services, NEC",
    "8111": "Legal Services",
    "8200": "Educational Services",
    "8211": "Elementary & Secondary Schools",
    "8220": "Colleges & Universities",
    "8231": "Libraries",
    "8300": "Social Services",
    "8351": "Child Day Care Services",
    "8600": "Membership Organizations",
    "8700": "Engineering & Accounting Services",
    "8711": "Engineering Services",
    "8712": "Architectural Services",
    "8721": "Accounting, Auditing & Bookkeeping Services",
    "8731": "Commercial Physical & Biological Research",
    "8734": "Testing Laboratories",
    "8741": "Management Services",
    "8742": "Management Consulting Services",
    "8744": "Facilities Support Management Services",
    "8900": "Miscellaneous Services",
    "8999": "Services, NEC",
    "9100": "Executive, Legislative & General Government",
    "9200": "Justice, Public Order & Safety",
    "9621": "Regulation of Utilities",
    "9711": "National Security",
    "9995": "Nonclassifiable Establishments",
}


def sic_to_subindustry(sic_code):
    """Return the 4-digit SIC industry description, or fall back to 2-digit major group."""
    sic = str(sic_code).zfill(4)
    if sic in SIC_INDUSTRIES:
        return SIC_INDUSTRIES[sic]
    major = sic[:2]
    return SIC_MAJOR_GROUPS.get(major, "")
