"""Generate requirements.lock with pinned versions + sha256 hashes from a pip --report JSON.

Usage: python scripts/gen_lockfile.py report.json requirements.lock
"""
from __future__ import annotations

import json
import sys
from pathlib import Path


def main(report_path: str, out_path: str) -> int:
    report = json.loads(Path(report_path).read_text(encoding="utf-8"))
    lines: list[str] = []
    for install in report.get("install", []):
        meta = install.get("metadata", {})
        name = meta.get("name")
        version = meta.get("version")
        dl = install.get("download_info", {})
        url = dl.get("url", "")
        archive = dl.get("archive_info", {})
        hashes = archive.get("hashes", {}) or {}
        sha256 = hashes.get("sha256") or archive.get("hash", "").removeprefix("sha256=")
        # Skip the project itself (local editable install)
        if url.startswith("file://") or not sha256:
            continue
        lines.append(f"{name}=={version} \\\n    --hash=sha256:{sha256}")

    lines.sort()
    out = "# Auto-generated by scripts/gen_lockfile.py from pip --report.\n"
    out += "# Do not edit by hand. Regenerate by running:\n"
    out += "#   pip install --dry-run --report report.json --ignore-installed -e .\n"
    out += "#   python scripts/gen_lockfile.py report.json requirements.lock\n\n"
    out += "\n".join(lines) + "\n"
    Path(out_path).write_text(out, encoding="utf-8")
    print(f"Wrote {len(lines)} pinned entries to {out_path}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1], sys.argv[2]))
